// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEfQYkEPE-_aYXJemmoHhSn_UGKGN7o58',
    appId: '1:402389755012:web:8f3e07b8a4fb7235b40ed1',
    messagingSenderId: '402389755012',
    projectId: 'podcast-awesome',
    authDomain: 'podcast-awesome.firebaseapp.com',
    storageBucket: 'podcast-awesome.appspot.com',
    measurementId: 'G-B49BJRR6KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGevMus3hSI8WRO8iyzI9blME-GefrM4A',
    appId: '1:402389755012:android:a1606f0f8eac75e6b40ed1',
    messagingSenderId: '402389755012',
    projectId: 'podcast-awesome',
    storageBucket: 'podcast-awesome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2_WAv9C7DcT_Lon6QqcNUbOMORVFA7y4',
    appId: '1:402389755012:ios:86b32c31316ff23ab40ed1',
    messagingSenderId: '402389755012',
    projectId: 'podcast-awesome',
    storageBucket: 'podcast-awesome.appspot.com',
    iosClientId: '402389755012-0m5b8daun3tle60bkk87eju9ptgs8k9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.podcastAwesome',
  );
}
